version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Google.Protobuf
    versions:
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.4
    - 3.15.7
  - dependency-name: Analogy.LogServer.Clients
    versions:
    - 0.5.5
  - dependency-name: NLog.Web.AspNetCore
    versions:
    - 4.11.0
